version: '3'
services:
  web:
    build: .
    ports:
      - "3001:80"
    volumes:
      - ${PWD}:/var/www/html
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./my-db/:/var/lib/mysql:rw
      - ./data/cinema.sql:/docker-entrypoint-initdb.d/cinema.sql
volumes:
  my-db:

